# 1. Carga de Datos

## 1.1 Carga

In [6]:
import pandas as pd
import numpy as np

In [9]:
base = pd.read_csv("C:/Users/S74010/Python/Modelo_DepositoPlazo/data/KF_BA_DEPPL_MODEL_DS.csv", sep = ',', encoding='latin-1')
base.shape

(330203, 60)

In [10]:
base.head()

,ID_SEC,TARGET_VTAMOV,CODSUBSEGMENTO,PERFIL_TACTICO,PERFIL_DIGITAL,FLGSEXO,TIPESTCIVIL,TIPNIVELEDUCACIONAL,TIPSITUACIONLABORAL,EDAD,...,TRX_DIG,TOTALTRX,TRX_VEN_MON,TRX_VEN_NOMON,TRX_NODIG_MON,TRX_NODIG_NOMON,TRX_DIG_MON,TRX_DIG_NOMON,TOTALTRX_MON,TOTALTRX_NOMON
0,1,0,X1N,ENALTA,DIG MON,M,SOL,BAC,DEP,37,...,242.0,267.0,6.0,0.0,19.0,0.0,57.0,185.0,82.0,185.0
1,2,0,M1N,CONSUMO,DIG MON,F,SOL,LIC,DEP,38,...,14.0,53.0,3.0,0.0,33.0,3.0,2.0,12.0,38.0,15.0
2,3,0,X1N,EXCLUSIVO ALTO POTENCIAL,DIG MON,F,CAS,BAC,DEP,43,...,58.0,79.0,2.0,0.0,19.0,0.0,13.0,45.0,34.0,45.0
3,4,0,X1N,EXCLUSIVO,DIG MON,F,CAS,BAC,NDI,43,...,290.0,314.0,2.0,0.0,15.0,7.0,18.0,272.0,35.0,279.0
4,5,0,M1N,CONSUMO,DIG MON,F,SOL,TEC,IND,42,...,83.0,87.0,0.0,0.0,4.0,0.0,11.0,72.0,15.0,72.0

In [11]:
base['TARGET_VTAMOV'].value_counts()

0    329483
1       720
Name: TARGET_VTAMOV, dtype: int64

## 1.2 Revisión Inicial

In [14]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330203 entries, 0 to 330202
Data columns (total 60 columns):
ID_SEC                  330203 non-null int64
TARGET_VTAMOV           330203 non-null int64
CODSUBSEGMENTO          330203 non-null object
PERFIL_TACTICO          329788 non-null object
PERFIL_DIGITAL          330203 non-null object
FLGSEXO                 330202 non-null object
TIPESTCIVIL             330203 non-null object
TIPNIVELEDUCACIONAL     330203 non-null object
TIPSITUACIONLABORAL     330203 non-null object
EDAD                    330203 non-null int64
CODUBIGEO               329928 non-null float64
DEPARTAMENTO            329928 non-null object
MESES_CLI               329788 non-null float64
INGRESO_TABLA_BCAPER    317482 non-null float64
FLG_AFLUENTE            329788 non-null float64
PERFIL_TACTICO_NUEVO    329788 non-null object
FLG_PASIVO              329788 non-null float64
FLG_ACTIVO              329788 non-null float64
FLG_INVERSION           329788 non-null float64
FLG_ACT_PAS             329788 non-null object
FLG_PREST_PER           329788 non-null float64
FLG_TC                  329788 non-null float64
FLG_HIP                 329788 non-null float64
FLG_CTASUELDO           329788 non-null float64
FLG_CTAAHORRO           329788 non-null float64
FLG_FFMM                329788 non-null float64
CANT_FAMPROD            329788 non-null float64
SALDO_PASIVO            329788 non-null float64
SALDO_ACTIVO            329788 non-null float64
SALDO_ACTIVO_SINHIP     329788 non-null float64
SALDO_INVERSION         329788 non-null float64
SALDO_PASIVO_N_6M       329668 non-null float64
FLG_ACT_PAS_SALDO       329788 non-null object
SALDO_PREST_PER         329788 non-null float64
SALDO_TC                329788 non-null float64
SALDO_HIP               329788 non-null float64
SALDO_CTASUELDO         329788 non-null float64
SALDO_CTAAHORRO         329788 non-null float64
SALDO_FFMM              329788 non-null float64
RCC_D_VEH               258768 non-null float64
RCC_D_HIP               258768 non-null float64
RCC_D_TC                258768 non-null float64
RCC_D_TOTAL             258768 non-null float64
TRX_VEN                 319925 non-null float64
TRX_ATM                 319925 non-null float64
TRX_AGE                 319925 non-null float64
TRX_BPT                 319925 non-null float64
TRX_HBK                 319925 non-null float64
TRX_BMO                 319925 non-null float64
TRX_NODIG               319925 non-null float64
TRX_DIG                 319925 non-null float64
TOTALTRX                319925 non-null float64
TRX_VEN_MON             319925 non-null float64
TRX_VEN_NOMON           319925 non-null float64
TRX_NODIG_MON           319925 non-null float64
TRX_NODIG_NOMON         319925 non-null float64
TRX_DIG_MON             319925 non-null float64
TRX_DIG_NOMON           319925 non-null float64
TOTALTRX_MON            319925 non-null float64
TOTALTRX_NOMON          319925 non-null float64
dtypes: float64(46), int64(3), object(11)
memory usage: 151.2+ MB

In [15]:
base.describe()

,ID_SEC,TARGET_VTAMOV,EDAD,CODUBIGEO,MESES_CLI,INGRESO_TABLA_BCAPER,FLG_AFLUENTE,FLG_PASIVO,FLG_ACTIVO,FLG_INVERSION,...,TRX_DIG,TOTALTRX,TRX_VEN_MON,TRX_VEN_NOMON,TRX_NODIG_MON,TRX_NODIG_NOMON,TRX_DIG_MON,TRX_DIG_NOMON,TOTALTRX_MON,TOTALTRX_NOMON
count,330203.000000,330203.000000,330203.000000,329928.000000,329788.000000,317482.000000,329788.000000,329788.000000,329788.000000,329788.000000,...,319925.000000,319925.000000,319925.000000,319925.000000,319925.000000,319925.000000,319925.000000,319925.000000,319925.000000,319925.000000
mean,165102.000000,0.002180,36.122955,138765.075535,101.421034,5294.383840,0.370405,0.998545,0.604643,0.049417,...,166.862199,192.969643,2.592642,0.121028,20.728336,2.613806,21.513045,145.349154,44.885654,148.083988
std,95321.539806,0.046645,10.302277,36343.247533,66.742392,7434.827898,0.482914,0.038123,0.488928,0.216737,...,208.930111,217.924522,6.734596,0.504025,22.110588,12.258253,34.277462,183.798936,46.209376,184.828308
min,1.000000,0.000000,0.000000,10101.000000,0.000000,350.010000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,82551.500000,0.000000,28.000000,150103.000000,49.000000,1809.530000,0.000000,1.000000,0.000000,0.000000,...,53.000000,74.000000,0.000000,0.000000,7.000000,0.000000,4.000000,46.000000,19.000000,48.000000
50%,165102.000000,0.000000,34.000000,150121.000000,85.000000,3244.745000,0.000000,1.000000,1.000000,0.000000,...,122.000000,148.000000,1.000000,0.000000,17.000000,1.000000,14.000000,105.000000,37.000000,107.000000
75%,247652.500000,0.000000,42.000000,150135.000000,145.000000,5916.418750,1.000000,1.000000,1.000000,0.000000,...,222.000000,253.000000,3.000000,0.000000,29.000000,3.000000,29.000000,193.000000,60.000000,195.000000
max,330203.000000,1.000000,117.000000,250302.000000,572.000000,501995.000000,1.000000,1.000000,1.000000,1.000000,...,28325.000000,28764.000000,768.000000,41.000000,3495.000000,2272.000000,3185.000000,27724.000000,3533.000000,27966.000000

In [114]:
vars_revision_group = ['CODSUBSEGMENTO',
'PERFIL_TACTICO',
'PERFIL_DIGITAL',
'FLGSEXO',
'TIPESTCIVIL',
'TIPNIVELEDUCACIONAL',
'TIPSITUACIONLABORAL',
'EDAD',
'CODUBIGEO',
'DEPARTAMENTO',
'MESES_CLI',
'FLG_AFLUENTE',
'PERFIL_TACTICO_NUEVO',
'FLG_PASIVO',
'FLG_ACTIVO',
'FLG_INVERSION',
'FLG_ACT_PAS',
'FLG_PREST_PER',
'FLG_TC',
'FLG_HIP',
'FLG_CTASUELDO',
'FLG_CTAAHORRO',
'FLG_FFMM',
'CANT_FAMPROD',
'FLG_ACT_PAS_SALDO']

# 2. Preparacion de Datos

In [115]:
cont = 0
for y in vars_revision_group:
    cont = cont + 1
    print("------------------------------------------------------")
    print(str(cont),". Var: ",y, sep = "")
    print(pd.concat([pd.DataFrame(base[:][y].value_counts().index, columns = ['Atributo']),
           pd.DataFrame(base[:][y].value_counts().values, columns = ['Cantidad']),
           pd.DataFrame(100*base[:][y].value_counts().values/len(base), columns = ['%Total'])], axis = 1))

------------------------------------------------------
1. Var: CODSUBSEGMENTO
  Atributo  Cantidad     %Total
0      M1N    228419  69.175325
1      X1N     89465  27.093939
2      LEN     11716   3.548120
3      P1N       603   0.182615
------------------------------------------------------
2. Var: PERFIL_TACTICO
                    Atributo  Cantidad     %Total
0              CONSUMO JOVEN     81289  24.617887
1                    CONSUMO     53402  16.172476
2     JÓVENES ALTO POTENCIAL     47843  14.488966
3                TOP CONSUMO     45086  13.654025
4   EXCLUSIVO ALTO POTENCIAL     31452   9.525050
5                  EXCLUSIVO     26676   8.078667
6                   SIN INFO     12338   3.736489
7             BAJOS INGRESOS     12010   3.637157
8                     ENALTA     10192   3.086586
9                 ESTUDIANTE      5323   1.612039
10                  JUBILADO      2553   0.773161
11              JUBILADO TOP      1624   0.491819
------------------------------------------------------
3. Var: PERFIL_DIGITAL
    Atributo  Cantidad     %Total
0    DIG MON    272711  82.588892
1  DIG NOMON     33892  10.263989
2     NO DIG     23600   7.147119
------------------------------------------------------
4. Var: FLGSEXO
  Atributo  Cantidad     %Total
0        M    208567  63.163266
1        F    121635  36.836431
------------------------------------------------------
5. Var: TIPESTCIVIL
  Atributo  Cantidad     %Total
0      SOL    224323  67.934876
1      CAS     87601  26.529438
2      SEP      8861   2.683501
3      CBS      4470   1.353713
4      CON      3754   1.136876
5      VIU      1194   0.361596
------------------------------------------------------
6. Var: TIPNIVELEDUCACIONAL
   Atributo  Cantidad     %Total
0       BAC     99242  30.054845
1       TEC     60686  18.378391
2       TIT     58006  17.566770
3       SUP     52886  16.016208
4       NDI     23099   6.995394
5       TEI     11869   3.594456
6       SEC      9531   2.886406
7       MAE      7782   2.356732
8       LIC      5549   1.680481
9       FAR       707   0.214111
10      DOC       676   0.204723
11      PRI       143   0.043307
12      ANA        27   0.008177
------------------------------------------------------
7. Var: TIPSITUACIONLABORAL
  Atributo  Cantidad     %Total
0      DEP    231233  70.027529
1      SUC     29491   8.931173
2      IND     24027   7.276433
3      NDI     21335   6.461177
4      EST     20315   6.152276
5      INF      2506   0.758927
6      JUB      1296   0.392486
------------------------------------------------------
8. Var: EDAD
    Atributo  Cantidad    %Total
0         28     17174  5.201043
1         29     16954  5.134417
2         30     16098  4.875183
3         31     14851  4.497536
4         32     14305  4.332184
5         27     14289  4.327338
6         26     13538  4.099902
7         33     13464  4.077492
8         34     13431  4.067498
9         35     12945  3.920316
10        36     12039  3.645939
11        25     11872  3.595364
12        37     11292  3.419715
13        38     10823  3.277681
14        39     10140  3.070838
15        24      9584  2.902457
16        40      9330  2.825535
17        41      8627  2.612635
18        42      7995  2.421238
19        43      7286  2.206521
20        23      6686  2.024815
21        44      6259  1.895501
22        45      5630  1.705012
23        46      5163  1.563584
24        47      4621  1.399442
25        22      4505  1.364312
26        48      4302  1.302835
27        49      3883  1.175943
28        50      3536  1.070856
29        51      3318  1.004836
..       ...       ...       ...
64        82        29  0.008782
65        84        28  0.008480
66        83        14  0.004240
67        85        14  0.004240
68        87        13  0.003937
69       117        11  0.003331
70        86        10  0.003028
71        89         7  0.002120
72        90         6  0.001817
73        91         6  0.001817
74        88         5  0.001514
75        95         3  0.000909
76         5         3  0.000909
77        13         2  0.000606
78         8         2  0.000606
79        92         2  0.000606
80       105         2  0.000606
81         3         2  0.000606
82         1         1  0.000303
83         2         1  0.000303
84         4         1  0.000303
85         7         1  0.000303
86       116         1  0.000303
87         9         1  0.000303
88        10         1  0.000303
89        11         1  0.000303
90        17         1  0.000303
91       114         1  0.000303
92       112         1  0.000303
93         0         1  0.000303

[94 rows x 3 columns]
------------------------------------------------------
9. Var: CODUBIGEO
     Atributo  Cantidad    %Total
0    150140.0     31060  9.406335
1    150122.0     15593  4.722247
2    150114.0     13592  4.116256
3    150135.0     13161  3.985730
4    150130.0     12414  3.759506
5    150132.0     12200  3.694697
6    150101.0     11296  3.420926
7    150131.0     10649  3.224986
8    150136.0      9705  2.939101
9    150117.0      9252  2.801913
10   150103.0      8892  2.692889
11    70101.0      8199  2.483018
12   150108.0      8108  2.455459
13   150110.0      7903  2.393376
14   130101.0      7554  2.287684
15   150133.0      6006  1.818881
16   150141.0      5870  1.777694
17   150121.0      5676  1.718943
18   150113.0      5341  1.617490
19   150120.0      4929  1.492718
20   150115.0      4864  1.473033
21   150142.0      4610  1.396111
22   150143.0      4582  1.387631
23   200101.0      4054  1.227730
24   140101.0      3734  1.130820
25   150116.0      3632  1.099929
26   150137.0      3513  1.063891
27   150128.0      3244  0.982426
28   150106.0      2810  0.850992
29   150105.0      2758  0.835244
..        ...       ...       ...
819   80407.0         1  0.000303
820  240202.0         1  0.000303
821  100508.0         1  0.000303
822  100507.0         1  0.000303
823  100501.0         1  0.000303
824  210105.0         1  0.000303
825   20109.0         1  0.000303
826  100317.0         1  0.000303
827   80501.0         1  0.000303
828   80505.0         1  0.000303
829   80506.0         1  0.000303
830  200606.0         1  0.000303
831  100701.0         1  0.000303
832  100803.0         1  0.000303
833  100804.0         1  0.000303
834   80305.0         1  0.000303
835   80304.0         1  0.000303
836   50404.0         1  0.000303
837   50407.0         1  0.000303
838   40127.0         1  0.000303
839   50502.0         1  0.000303
840  101104.0         1  0.000303
841   50804.0         1  0.000303
842   50910.0         1  0.000303
843   40115.0         1  0.000303
844   40114.0         1  0.000303
845   40113.0         1  0.000303
846   51005.0         1  0.000303
847   51106.0         1  0.000303
848  131007.0         1  0.000303

[849 rows x 3 columns]
------------------------------------------------------
10. Var: DEPARTAMENTO
                     Atributo  Cantidad     %Total
0   LIMA                         242974  73.583220
1   CALLAO                        16242   4.918792
2   AREQUIPA                      14700   4.451807
3   LA LIBERTAD                   12552   3.801298
4   PIURA                          7759   2.349767
5   LAMBAYEQUE                     5817   1.761644
6   ICA                            4122   1.248323
7   CUZCO                          3561   1.078428
8   ANCASH                         3508   1.062377
9   JUNIN                          3314   1.003625
10  CAJAMARCA                      2853   0.864014
11  TACNA                          1876   0.568135
12  MOQUEGUA                       1867   0.565410
13  SAN MARTIN                     1475   0.446695
14  LORETO                         1428   0.432461
15  HUANUCO                        1039   0.314655
16  UCAYALI                        1014   0.307084
17  PUNO                            985   0.298301
18  AYACUCHO                        754   0.228344
19  TUMBES                          431   0.130526
20  CERRO DE PASCO                  409   0.123863
21  AMAZONAS                        399   0.120835
22  APURIMAC                        379   0.114778
23  MADRE DE DIOS                   295   0.089339
24  HUANCAVELICA                    175   0.052998
------------------------------------------------------
11. Var: MESES_CLI
     Atributo  Cantidad    %Total
0        50.0      3131  0.948205
1        51.0      3081  0.933062
2        53.0      3042  0.921251
3        49.0      2977  0.901567
4        70.0      2977  0.901567
5        61.0      2821  0.854323
6        52.0      2779  0.841603
7        41.0      2724  0.824947
8        72.0      2722  0.824341
9        47.0      2695  0.816165
10       46.0      2627  0.795571
11       63.0      2625  0.794966
12       58.0      2619  0.793148
13       65.0      2610  0.790423
14       71.0      2582  0.781943
15       64.0      2557  0.774372
16       56.0      2515  0.761653
17       59.0      2509  0.759836
18       55.0      2502  0.757716
19       62.0      2475  0.749539
20       39.0      2440  0.738939
21       45.0      2418  0.732277
22       57.0      2395  0.725311
23       48.0      2378  0.720163
24       40.0      2366  0.716529
25       44.0      2360  0.714712
26       29.0      2351  0.711986
27       37.0      2320  0.702598
28       75.0      2260  0.684427
29       73.0      2251  0.681702
..        ...       ...       ...
436     502.0         1  0.000303
437     392.0         1  0.000303
438     426.0         1  0.000303
439     388.0         1  0.000303
440     424.0         1  0.000303
441     356.0         1  0.000303
442     348.0         1  0.000303
443     536.0         1  0.000303
444     420.0         1  0.000303
445     379.0         1  0.000303
446     540.0         1  0.000303
447     470.0         1  0.000303
448     326.0         1  0.000303
449     401.0         1  0.000303
450     544.0         1  0.000303
451     416.0         1  0.000303
452     565.0         1  0.000303
453     546.0         1  0.000303
454     452.0         1  0.000303
455     557.0         1  0.000303
456     413.0         1  0.000303
457     382.0         1  0.000303
458     429.0         1  0.000303
459     549.0         1  0.000303
460     435.0         1  0.000303
461     439.0         1  0.000303
462     572.0         1  0.000303
463     547.0         1  0.000303
464     441.0         1  0.000303
465     511.0         1  0.000303

[466 rows x 3 columns]
------------------------------------------------------
12. Var: FLG_AFLUENTE
   Atributo  Cantidad    %Total
0       0.0    207633  62.88041
1       1.0    122155  36.99391

------------------------------------------------------
13. Var: PERFIL_TACTICO_NUEVO
                    Atributo  Cantidad     %Total
0              CONSUMO JOVEN     81112  24.564283
1                    CONSUMO     52004  15.749100
2     JÓVENES ALTO POTENCIAL     47591  14.412649
3                TOP CONSUMO     44576  13.499575
4   EXCLUSIVO ALTO POTENCIAL     29144   8.826086
5                  EXCLUSIVO     26171   7.925731
6                   SIN INFO     12336   3.735884
7             BAJOS INGRESOS     11817   3.578708
8               ENALTA JOVEN      7174   2.172603
9              ENALTA ADULTO      7151   2.165638
10                ESTUDIANTE      5316   1.609919
11                  JUBILADO      2284   0.691696
12             ENALTA SENIOR      1637   0.495756
13              JUBILADO TOP      1475   0.446695
------------------------------------------------------
14. Var: FLG_PASIVO
   Atributo  Cantidad     %Total
0       1.0    329308  99.728955
1       0.0       480   0.145365
------------------------------------------------------
15. Var: FLG_ACTIVO
   Atributo  Cantidad     %Total
0       1.0    199404  60.388307
1       0.0    130384  39.486013
------------------------------------------------------
16. Var: FLG_INVERSION
   Atributo  Cantidad     %Total
0       0.0    313491  94.938871
1       1.0     16297   4.935449
------------------------------------------------------
17. Var: FLG_ACT_PAS
  Atributo  Cantidad     %Total
0      A/P    199172  60.318047
1        P    130153  39.416056
2        A       232   0.070260
3  NO PROD       231   0.069957
------------------------------------------------------
18. Var: FLG_PREST_PER
   Atributo  Cantidad     %Total
0       0.0    271837  82.324207
1       1.0     57951  17.550113
------------------------------------------------------
19. Var: FLG_TC
   Atributo  Cantidad     %Total
0       1.0    185705  56.239647
1       0.0    144083  43.634673
------------------------------------------------------
20. Var: FLG_HIP
   Atributo  Cantidad     %Total
0       0.0    315068  95.416456
1       1.0     14720   4.457864
------------------------------------------------------
21. Var: FLG_CTASUELDO
   Atributo  Cantidad     %Total
0       0.0    174621  52.882924
1       1.0    155167  46.991396
------------------------------------------------------
22. Var: FLG_CTAAHORRO
   Atributo  Cantidad    %Total
0       1.0    243846  73.84730
1       0.0     85942  26.02702
------------------------------------------------------
23. Var: FLG_FFMM
   Atributo  Cantidad     %Total
0       0.0    318536  96.466719
1       1.0     11252   3.407601
------------------------------------------------------
24. Var: CANT_FAMPROD
   Atributo  Cantidad     %Total
0       2.0    106156  32.148709
1       1.0     85079  25.765665
2       3.0     78208  23.684824
3       4.0     42653  12.917205
4       5.0     14479   4.384878
5       6.0      2568   0.777703
6       7.0       373   0.112961
7       0.0       231   0.069957
8       8.0        41   0.012417
------------------------------------------------------
25. Var: FLG_ACT_PAS_SALDO
        Atributo  Cantidad     %Total
0            A/P    158013  47.853290
1              P    139843  42.350615
2  NO PROD SALDO     20870   6.320354
3              A     11062   3.350060

In [134]:
data = base.copy()

### 2.1 Tratamiento Nulos

In [135]:
pd.concat([pd.DataFrame(base.isnull().sum(), columns = ['cantidad']),
           pd.DataFrame(100*base.isnull().sum()/len(base), columns = ['%Total'])], axis = 1)

                      cantidad     %Total
ID_SEC                       0   0.000000
TARGET_VTAMOV                0   0.000000
CODSUBSEGMENTO               0   0.000000
PERFIL_TACTICO             415   0.125680
PERFIL_DIGITAL               0   0.000000
FLGSEXO                      1   0.000303
TIPESTCIVIL                  0   0.000000
TIPNIVELEDUCACIONAL          0   0.000000
TIPSITUACIONLABORAL          0   0.000000
EDAD                         0   0.000000
CODUBIGEO                  275   0.083282
DEPARTAMENTO               275   0.083282
MESES_CLI                  415   0.125680
INGRESO_TABLA_BCAPER     12721   3.852479
FLG_AFLUENTE               415   0.125680
PERFIL_TACTICO_NUEVO       415   0.125680
FLG_PASIVO                 415   0.125680
FLG_ACTIVO                 415   0.125680
FLG_INVERSION              415   0.125680
FLG_ACT_PAS                415   0.125680
FLG_PREST_PER              415   0.125680
FLG_TC                     415   0.125680
FLG_HIP                    415   0.125680
FLG_CTASUELDO              415   0.125680
FLG_CTAAHORRO              415   0.125680
FLG_FFMM                   415   0.125680
CANT_FAMPROD               415   0.125680
SALDO_PASIVO               415   0.125680
SALDO_ACTIVO               415   0.125680
SALDO_ACTIVO_SINHIP        415   0.125680
SALDO_INVERSION            415   0.125680
SALDO_PASIVO_N_6M          535   0.162022
FLG_ACT_PAS_SALDO          415   0.125680
SALDO_PREST_PER            415   0.125680
SALDO_TC                   415   0.125680
SALDO_HIP                  415   0.125680
SALDO_CTASUELDO            415   0.125680
SALDO_CTAAHORRO            415   0.125680
SALDO_FFMM                 415   0.125680
RCC_D_VEH                71435  21.633662
RCC_D_HIP                71435  21.633662
RCC_D_TC                 71435  21.633662
RCC_D_TOTAL              71435  21.633662
TRX_VEN                  10278   3.112631
TRX_ATM                  10278   3.112631
TRX_AGE                  10278   3.112631
TRX_BPT                  10278   3.112631
TRX_HBK                  10278   3.112631
TRX_BMO                  10278   3.112631
TRX_NODIG                10278   3.112631
TRX_DIG                  10278   3.112631
TOTALTRX                 10278   3.112631
TRX_VEN_MON              10278   3.112631
TRX_VEN_NOMON            10278   3.112631
TRX_NODIG_MON            10278   3.112631
TRX_NODIG_NOMON          10278   3.112631
TRX_DIG_MON              10278   3.112631
TRX_DIG_NOMON            10278   3.112631
TOTALTRX_MON             10278   3.112631
TOTALTRX_NOMON           10278   3.112631

In [149]:
pd.concat([pd.DataFrame(data.isnull().sum(), columns = ['cantidad']),
           pd.DataFrame(100*data.isnull().sum()/len(data), columns = ['%Total'])], axis = 1)

                      cantidad  %Total
ID_SEC                       0     0.0
TARGET_VTAMOV                0     0.0
CODSUBSEGMENTO               0     0.0
PERFIL_TACTICO               0     0.0
PERFIL_DIGITAL               0     0.0
FLGSEXO                      0     0.0
TIPESTCIVIL                  0     0.0
TIPNIVELEDUCACIONAL          0     0.0
TIPSITUACIONLABORAL          0     0.0
EDAD                         0     0.0
CODUBIGEO                    0     0.0
DEPARTAMENTO                 0     0.0
MESES_CLI                    0     0.0
INGRESO_TABLA_BCAPER         0     0.0
FLG_AFLUENTE                 0     0.0
PERFIL_TACTICO_NUEVO         0     0.0
FLG_PASIVO                   0     0.0
FLG_ACTIVO                   0     0.0
FLG_INVERSION                0     0.0
FLG_ACT_PAS                  0     0.0
FLG_PREST_PER                0     0.0
FLG_TC                       0     0.0
FLG_HIP                      0     0.0
FLG_CTASUELDO                0     0.0
FLG_CTAAHORRO                0     0.0
FLG_FFMM                     0     0.0
CANT_FAMPROD                 0     0.0
SALDO_PASIVO                 0     0.0
SALDO_ACTIVO                 0     0.0
SALDO_ACTIVO_SINHIP          0     0.0
SALDO_INVERSION              0     0.0
SALDO_PASIVO_N_6M            0     0.0
FLG_ACT_PAS_SALDO            0     0.0
SALDO_PREST_PER              0     0.0
SALDO_TC                     0     0.0
SALDO_HIP                    0     0.0
SALDO_CTASUELDO              0     0.0
SALDO_CTAAHORRO              0     0.0
SALDO_FFMM                   0     0.0
RCC_D_VEH                    0     0.0
RCC_D_HIP                    0     0.0
RCC_D_TC                     0     0.0
RCC_D_TOTAL                  0     0.0
TRX_VEN                      0     0.0
TRX_ATM                      0     0.0
TRX_AGE                      0     0.0
TRX_BPT                      0     0.0
TRX_HBK                      0     0.0
TRX_BMO                      0     0.0
TRX_NODIG                    0     0.0
TRX_DIG                      0     0.0
TOTALTRX                     0     0.0
TRX_VEN_MON                  0     0.0
TRX_VEN_NOMON                0     0.0
TRX_NODIG_MON                0     0.0
TRX_NODIG_NOMON              0     0.0
TRX_DIG_MON                  0     0.0
TRX_DIG_NOMON                0     0.0
TOTALTRX_MON                 0     0.0
TOTALTRX_NOMON               0     0.0

In [137]:
# PERFIL_TACTICO
feature = "PERFIL_TACTICO"
data[feature].fillna("SIN INFO", inplace=True)

In [138]:
# FLGSEXO
feature = "FLGSEXO"
data[feature].fillna("M", inplace=True)

In [139]:
# CODUBIGEO
feature = "CODUBIGEO"
data[feature].fillna(150140, inplace=True)

In [143]:
# DEPARTAMENTO
feature = "DEPARTAMENTO"
data[feature].fillna("LIMA", inplace=True)

In [140]:
# MESES_CLI
feature = "MESES_CLI"
data[feature].fillna(data[feature].median(), inplace=True)

In [141]:
# INGRESO_TABLA_BCAPER
feature = "INGRESO_TABLA_BCAPER"
data[feature].fillna(data[feature].median(), inplace=True)

In [145]:
# PERFIL_TACTICO_NUEVO
feature = "PERFIL_TACTICO_NUEVO"
data[feature].fillna("CONSUMO JOVEN", inplace=True)

In [147]:
# Resto de variables:
var_to_imputar_0 = ['FLG_AFLUENTE',
'FLG_PASIVO',
'FLG_ACTIVO',
'FLG_INVERSION',
'FLG_ACT_PAS',
'FLG_PREST_PER',
'FLG_TC',
'FLG_HIP',
'FLG_CTASUELDO',
'FLG_CTAAHORRO',
'FLG_FFMM',
'CANT_FAMPROD',
'SALDO_PASIVO',
'SALDO_ACTIVO',
'SALDO_ACTIVO_SINHIP',
'SALDO_INVERSION',
'SALDO_PASIVO_N_6M',
'FLG_ACT_PAS_SALDO',
'SALDO_PREST_PER',
'SALDO_TC',
'SALDO_HIP',
'SALDO_CTASUELDO',
'SALDO_CTAAHORRO',
'SALDO_FFMM',
'RCC_D_VEH',
'RCC_D_HIP',
'RCC_D_TC',
'RCC_D_TOTAL',
'TRX_VEN',
'TRX_ATM',
'TRX_AGE',
'TRX_BPT',
'TRX_HBK',
'TRX_BMO',
'TRX_NODIG',
'TRX_DIG',
'TOTALTRX',
'TRX_VEN_MON',
'TRX_VEN_NOMON',
'TRX_NODIG_MON',
'TRX_NODIG_NOMON',
'TRX_DIG_MON',
'TRX_DIG_NOMON',
'TOTALTRX_MON',
'TOTALTRX_NOMON']

In [148]:
for feature in var_to_imputar_0:
    data[feature].fillna(0, inplace=True)

### 2.2 Revisión Outliers

In [181]:
data.columns

Index(['ID_SEC', 'TARGET_VTAMOV', 'CODSUBSEGMENTO', 'PERFIL_TACTICO',
       'PERFIL_DIGITAL', 'FLGSEXO', 'TIPESTCIVIL', 'TIPNIVELEDUCACIONAL',
       'TIPSITUACIONLABORAL', 'EDAD', 'CODUBIGEO', 'DEPARTAMENTO', 'MESES_CLI',
       'INGRESO_TABLA_BCAPER', 'FLG_AFLUENTE', 'PERFIL_TACTICO_NUEVO',
       'FLG_PASIVO', 'FLG_ACTIVO', 'FLG_INVERSION', 'FLG_ACT_PAS',
       'FLG_PREST_PER', 'FLG_TC', 'FLG_HIP', 'FLG_CTASUELDO', 'FLG_CTAAHORRO',
       'FLG_FFMM', 'CANT_FAMPROD', 'SALDO_PASIVO', 'SALDO_ACTIVO',
       'SALDO_ACTIVO_SINHIP', 'SALDO_INVERSION', 'SALDO_PASIVO_N_6M',
       'FLG_ACT_PAS_SALDO', 'SALDO_PREST_PER', 'SALDO_TC', 'SALDO_HIP',
       'SALDO_CTASUELDO', 'SALDO_CTAAHORRO', 'SALDO_FFMM', 'RCC_D_VEH',
       'RCC_D_HIP', 'RCC_D_TC', 'RCC_D_TOTAL', 'TRX_VEN', 'TRX_ATM', 'TRX_AGE',
       'TRX_BPT', 'TRX_HBK', 'TRX_BMO', 'TRX_NODIG', 'TRX_DIG', 'TOTALTRX',
       'TRX_VEN_MON', 'TRX_VEN_NOMON', 'TRX_NODIG_MON', 'TRX_NODIG_NOMON',
       'TRX_DIG_MON', 'TRX_DIG_NOMON', 'TOTALTRX_MON', 'TOTALTRX_NOMON'],
      dtype='object')

In [182]:
vars_rev_ouliers = ['EDAD',
'MESES_CLI',
'CANT_FAMPROD',
'SALDO_PASIVO',
'SALDO_ACTIVO',
'SALDO_ACTIVO_SINHIP',
'SALDO_INVERSION',
'SALDO_PASIVO_N_6M',
'SALDO_PREST_PER',
'SALDO_TC',
'SALDO_HIP',
'SALDO_CTASUELDO',
'SALDO_CTAAHORRO',
'SALDO_FFMM',
'RCC_D_VEH',
'RCC_D_HIP',
'RCC_D_TC',
'RCC_D_TOTAL',
'TRX_VEN',
'TRX_ATM',
'TRX_AGE',
'TRX_BPT',
'TRX_HBK',
'TRX_BMO',
'TRX_NODIG',
'TRX_DIG',
'TOTALTRX',
'TRX_VEN_MON',
'TRX_VEN_NOMON',
'TRX_NODIG_MON',
'TRX_NODIG_NOMON',
'TRX_DIG_MON',
'TRX_DIG_NOMON',
'TOTALTRX_MON',
'TOTALTRX_NOMON']

In [190]:
vector_percentiles = [0,1,2.5,5,10,50,90,92.5,95,97.5,99,99.5,100]

In [191]:
cont = 0
for feature in vars_rev_ouliers:
    cont = cont + 1
    print("------------------------------------------------------")
    print(str(cont),". Var: ",feature, sep = "")
    print(pd.concat([pd.DataFrame(vector_percentiles, columns = ['Percentile']),
                     pd.DataFrame(np.nanpercentile(data[[feature]], vector_percentiles), columns = ['Valor'])], axis = 1))

------------------------------------------------------
1. Var: EDAD
    Percentile  Valor
0          0.0    0.0
1          1.0   21.0
2          2.5   22.0
3          5.0   23.0
4         10.0   25.0
5         50.0   34.0
6         90.0   51.0
7         92.5   54.0
8         95.0   57.0
9         97.5   62.0
10        99.0   67.0
11        99.5   70.0
12       100.0  117.0
------------------------------------------------------
2. Var: MESES_CLI
    Percentile  Valor
0          0.0    0.0
1          1.0    8.0
2          2.5   13.0
3          5.0   19.0
4         10.0   28.0
5         50.0   85.0
6         90.0  195.0
7         92.5  208.0
8         95.0  229.0
9         97.5  253.0
10        99.0  292.0
11        99.5  310.0
12       100.0  572.0
------------------------------------------------------
3. Var: CANT_FAMPROD
    Percentile  Valor
0          0.0    0.0
1          1.0    1.0
2          2.5    1.0
3          5.0    1.0
4         10.0    1.0
5         50.0    2.0
6         90.0    4.0
7         92.5    4.0
8         95.0    5.0
9         97.5    5.0
10        99.0    5.0
11        99.5    6.0
12       100.0    8.0
------------------------------------------------------
4. Var: SALDO_PASIVO
    Percentile         Valor
0          0.0  0.000000e+00
1          1.0  0.000000e+00
2          2.5  0.000000e+00
3          5.0  4.600000e-01
4         10.0  1.116000e+01
5         50.0  1.477610e+03
6         90.0  3.317147e+04
7         92.5  4.528160e+04
8         95.0  6.760037e+04
9         97.5  1.259110e+05
10        99.0  2.528282e+05
11        99.5  3.907254e+05
12       100.0  4.987802e+07
------------------------------------------------------
5. Var: SALDO_ACTIVO
    Percentile         Valor
0          0.0  0.000000e+00
1          1.0  0.000000e+00
2          2.5  0.000000e+00
3          5.0  0.000000e+00
4         10.0  0.000000e+00
5         50.0  4.753000e+01
6         90.0  4.617442e+04
7         92.5  6.230487e+04
8         95.0  8.696942e+04
9         97.5  2.120201e+05
10        99.0  4.619005e+05
11        99.5  6.794843e+05
12       100.0  1.664586e+07
------------------------------------------------------
6. Var: SALDO_ACTIVO_SINHIP
    Percentile         Valor
0          0.0  0.000000e+00
1          1.0  0.000000e+00
2          2.5  0.000000e+00
3          5.0  0.000000e+00
4         10.0  0.000000e+00
5         50.0  8.200000e-01
6         90.0  3.279803e+04
7         92.5  4.303094e+04
8         95.0  5.702223e+04
9         97.5  7.767235e+04
10        99.0  1.129205e+05
11        99.5  1.667995e+05
12       100.0  1.664586e+07
------------------------------------------------------
7. Var: SALDO_INVERSION
    Percentile         Valor
0          0.0  0.000000e+00
1          1.0  0.000000e+00
2          2.5  0.000000e+00
3          5.0  0.000000e+00
4         10.0  0.000000e+00
5         50.0  0.000000e+00
6         90.0  0.000000e+00
7         92.5  0.000000e+00
8         95.0  0.000000e+00
9         97.5  2.260915e+04
10        99.0  1.315558e+05
11        99.5  3.380850e+05
12       100.0  8.642456e+07
------------------------------------------------------
8. Var: SALDO_PASIVO_N_6M
    Percentile         Valor
0          0.0  0.000000e+00
1          1.0  1.200000e-01
2          2.5  2.498417e+00
3          5.0  1.500683e+01
4         10.0  6.463667e+01
5         50.0  1.938993e+03
6         90.0  3.783624e+04
7         92.5  5.284274e+04
8         95.0  8.277115e+04
9         97.5  1.656836e+05
10        99.0  3.738420e+05
11        99.5  6.677182e+05
12       100.0  9.565155e+07
------------------------------------------------------
9. Var: SALDO_PREST_PER
    Percentile         Valor
0          0.0  0.000000e+00
1          1.0  0.000000e+00
2          2.5  0.000000e+00
3          5.0  0.000000e+00
4         10.0  0.000000e+00
5         50.0  0.000000e+00
6         90.0  1.585822e+04
7         92.5  2.481131e+04
8         95.0  3.765301e+04
9         97.5  5.825232e+04
10        99.0  8.719182e+04
11        99.5  1.374983e+05
12       100.0  1.657570e+07
------------------------------------------------------
10. Var: SALDO_TC
    Percentile        Valor
0          0.0       0.0000
1          1.0       0.0000
2          2.5       0.0000
3          5.0       0.0000
4         10.0       0.0000
5         50.0       0.0000
6         90.0   12968.9940
7         92.5   18328.2405
8         95.0   27035.2560
9         97.5   43722.8750
10        99.0   65477.2698
11        99.5   77502.3189
12       100.0  330062.0000
------------------------------------------------------
11. Var: SALDO_HIP
    Percentile         Valor
0          0.0  0.000000e+00
1          1.0  0.000000e+00
2          2.5  0.000000e+00
3          5.0  0.000000e+00
4         10.0  0.000000e+00
5         50.0  0.000000e+00
6         90.0  0.000000e+00
7         92.5  0.000000e+00
8         95.0  0.000000e+00
9         97.5  1.640086e+05
10        99.0  3.936433e+05
11        99.5  5.956124e+05
12       100.0  7.539372e+06
------------------------------------------------------
12. Var: SALDO_CTASUELDO
    Percentile         Valor
0          0.0  0.000000e+00
1          1.0  0.000000e+00
2          2.5  0.000000e+00
3          5.0  0.000000e+00
4         10.0  0.000000e+00
5         50.0  0.000000e+00
6         90.0  3.623810e+03
7         92.5  5.613557e+03
8         95.0  1.002715e+04
9         97.5  2.304366e+04
10        99.0  5.377040e+04
11        99.5  9.205620e+04
12       100.0  3.802919e+06
------------------------------------------------------
13. Var: SALDO_CTAAHORRO
    Percentile         Valor
0          0.0  0.000000e+00
1          1.0  0.000000e+00
2          2.5  0.000000e+00
3          5.0  0.000000e+00
4         10.0  0.000000e+00
5         50.0  8.232000e+01
6         90.0  1.204725e+04
7         92.5  1.911736e+04
8         95.0  3.371674e+04
9         97.5  7.393061e+04
10        99.0  1.715087e+05
11        99.5  2.942241e+05
12       100.0  4.981420e+07
------------------------------------------------------
14. Var: SALDO_FFMM
    Percentile         Valor
0          0.0  0.000000e+00
1          1.0  0.000000e+00
2          2.5  0.000000e+00
3          5.0  0.000000e+00
4         10.0  0.000000e+00
5         50.0  0.000000e+00
6         90.0  0.000000e+00
7         92.5  0.000000e+00
8         95.0  0.000000e+00
9         97.5  6.592542e+03
10        99.0  7.623896e+04
11        99.5  2.031450e+05
12       100.0  2.587963e+07
------------------------------------------------------
15. Var: RCC_D_VEH
    Percentile        Valor
0          0.0       0.0000
1          1.0       0.0000
2          2.5       0.0000
3          5.0       0.0000
4         10.0       0.0000
5         50.0       0.0000
6         90.0       0.0000
7         92.5       0.0000
8         95.0    9397.9780
9         97.5   32951.8085
10        99.0   53939.1722
11        99.5   69892.6146
12       100.0  692550.5800
------------------------------------------------------
16. Var: RCC_D_HIP
    Percentile         Valor
0          0.0  0.000000e+00
1          1.0  0.000000e+00
2          2.5  0.000000e+00
3          5.0  0.000000e+00
4         10.0  0.000000e+00
5         50.0  0.000000e+00
6         90.0  1.148305e+04
7         92.5  9.546186e+04
8         95.0  1.785230e+05
9         97.5  3.361636e+05
10        99.0  5.849754e+05
11        99.5  8.105116e+05
12       100.0  1.190190e+07
------------------------------------------------------
17. Var: RCC_D_TC
    Percentile        Valor
0          0.0       0.0000
1          1.0       0.0000
2          2.5       0.0000
3          5.0       0.0000
4         10.0       0.0000
5         50.0    1409.0500
6         90.0   29649.4160
7         92.5   37922.5440
8         95.0   51285.9880
9         97.5   77887.2760
10        99.0  118889.3514
11        99.5  152525.9023
12       100.0  541395.5100
------------------------------------------------------
18. Var: RCC_D_TOTAL
    Percentile         Valor
0          0.0  0.000000e+00
1          1.0  0.000000e+00
2          2.5  0.000000e+00
3          5.0  0.000000e+00
4         10.0  0.000000e+00
5         50.0  4.616340e+03
6         90.0  1.134472e+05
7         92.5  1.579694e+05
8         95.0  2.352564e+05
9         97.5  4.029625e+05
10        99.0  6.759896e+05
11        99.5  9.292031e+05
12       100.0  1.666869e+07
------------------------------------------------------
19. Var: TRX_VEN
    Percentile  Valor
0          0.0    0.0
1          1.0    0.0
2          2.5    0.0
3          5.0    0.0
4         10.0    0.0
5         50.0    1.0
6         90.0    7.0
7         92.5    8.0
8         95.0   11.0
9         97.5   16.0
10        99.0   25.0
11        99.5   35.0
12       100.0  769.0
------------------------------------------------------
20. Var: TRX_ATM
    Percentile   Valor
0          0.0    0.00
1          1.0    0.00
2          2.5    0.00
3          5.0    0.00
4         10.0    0.00
5         50.0   15.00
6         90.0   41.00
7         92.5   45.00
8         95.0   51.00
9         97.5   63.00
10        99.0   80.00
11        99.5   94.99
12       100.0  613.00
------------------------------------------------------
21. Var: TRX_AGE
    Percentile   Valor
0          0.0     0.0
1          1.0     0.0
2          2.5     0.0
3          5.0     0.0
4         10.0     0.0
5         50.0     1.0
6         90.0    10.0
7         92.5    13.0
8         95.0    16.0
9         97.5    24.0
10        99.0    35.0
11        99.5    46.0
12       100.0  4101.0
------------------------------------------------------
22. Var: TRX_BPT
    Percentile  Valor
0          0.0    0.0
1          1.0    0.0
2          2.5    0.0
3          5.0    0.0
4         10.0    0.0
5         50.0    0.0
6         90.0    0.0
7         92.5    0.0
8         95.0    0.0
9         97.5    0.0
10        99.0    0.0
11        99.5    0.0
12       100.0    8.0
------------------------------------------------------
23. Var: TRX_HBK
    Percentile    Valor
0          0.0      0.0
1          1.0      0.0
2          2.5      0.0
3          5.0      0.0
4         10.0      0.0
5         50.0     10.0
6         90.0    131.0
7         92.5    157.0
8         95.0    196.0
9         97.5    269.0
10        99.0    386.0
11        99.5    496.0
12       100.0  25162.0
------------------------------------------------------
24. Var: TRX_BMO
    Percentile     Valor
0          0.0      0.00
1          1.0      0.00
2          2.5      0.00
3          5.0      0.00
4         10.0      0.00
5         50.0     66.00
6         90.0    293.00
7         92.5    335.00
8         95.0    397.00
9         97.5    516.00
10        99.0    701.00
11        99.5    881.99
12       100.0  21433.00
------------------------------------------------------
25. Var: TRX_NODIG
    Percentile   Valor
0          0.0     0.0
1          1.0     0.0
2          2.5     0.0
3          5.0     0.0
4         10.0     1.0
5         50.0    18.0
6         90.0    47.0
7         92.5    53.0
8         95.0    60.0
9         97.5    73.0
10        99.0    95.0
11        99.5   115.0
12       100.0  4264.0
------------------------------------------------------
26. Var: TRX_DIG
    Percentile    Valor
0          0.0      0.0
1          1.0      0.0
2          2.5      0.0
3          5.0      0.0
4         10.0      6.0
5         50.0    117.0
6         90.0    353.0
7         92.5    398.0
8         95.0    467.0
9         97.5    597.0
10        99.0    810.0
11        99.5   1017.0

12       100.0  28325.0
------------------------------------------------------
27. Var: TOTALTRX
    Percentile     Valor
0          0.0      0.00
1          1.0      0.00
2          2.5      0.00
3          5.0      3.00
4         10.0     17.00
5         50.0    143.00
6         90.0    388.80
7         92.5    436.00
8         95.0    508.00
9         97.5    643.00
10        99.0    864.00
11        99.5   1081.99
12       100.0  28764.00
------------------------------------------------------
28. Var: TRX_VEN_MON
    Percentile  Valor
0          0.0    0.0
1          1.0    0.0
2          2.5    0.0
3          5.0    0.0
4         10.0    0.0
5         50.0    1.0
6         90.0    7.0
7         92.5    8.0
8         95.0   10.0
9         97.5   15.0
10        99.0   24.0
11        99.5   34.0
12       100.0  768.0
------------------------------------------------------
29. Var: TRX_VEN_NOMON
    Percentile  Valor
0          0.0    0.0
1          1.0    0.0
2          2.5    0.0
3          5.0    0.0
4         10.0    0.0
5         50.0    0.0
6         90.0    0.0
7         92.5    1.0
8         95.0    1.0
9         97.5    1.0
10        99.0    2.0
11        99.5    3.0
12       100.0   41.0
------------------------------------------------------
30. Var: TRX_NODIG_MON
    Percentile   Valor
0          0.0     0.0
1          1.0     0.0
2          2.5     0.0
3          5.0     0.0
4         10.0     1.0
5         50.0    16.0
6         90.0    43.0
7         92.5    47.0
8         95.0    54.0
9         97.5    65.0
10        99.0    83.0
11        99.5    98.0
12       100.0  3495.0
------------------------------------------------------
31. Var: TRX_NODIG_NOMON
    Percentile   Valor
0          0.0     0.0
1          1.0     0.0
2          2.5     0.0
3          5.0     0.0
4         10.0     0.0
5         50.0     1.0
6         90.0     6.0
7         92.5     8.0
8         95.0    10.0
9         97.5    15.0
10        99.0    23.0
11        99.5    31.0
12       100.0  2272.0
------------------------------------------------------
32. Var: TRX_DIG_MON
    Percentile   Valor
0          0.0     0.0
1          1.0     0.0
2          2.5     0.0
3          5.0     0.0
4         10.0     0.0
5         50.0    13.0
6         90.0    48.0
7         92.5    54.0
8         95.0    65.0
9         97.5    86.0
10        99.0   123.0
11        99.5   163.0
12       100.0  3185.0
------------------------------------------------------
33. Var: TRX_DIG_NOMON
    Percentile    Valor
0          0.0      0.0
1          1.0      0.0
2          2.5      0.0
3          5.0      0.0
4         10.0      5.0
5         50.0    101.0
6         90.0    309.0
7         92.5    350.0
8         95.0    411.0
9         97.5    525.0
10        99.0    711.0
11        99.5    885.0
12       100.0  27724.0
------------------------------------------------------
34. Var: TOTALTRX_MON
    Percentile   Valor
0          0.0     0.0
1          1.0     0.0
2          2.5     0.0
3          5.0     1.0
4         10.0     4.0
5         50.0    36.0
6         90.0    85.0
7         92.5    94.0
8         95.0   108.0
9         97.5   135.0
10        99.0   183.0
11        99.5   233.0
12       100.0  3533.0
------------------------------------------------------
35. Var: TOTALTRX_NOMON
    Percentile    Valor
0          0.0      0.0
1          1.0      0.0
2          2.5      0.0
3          5.0      1.0
4         10.0      8.0
5         50.0    103.0
6         90.0    312.0
7         92.5    352.0
8         95.0    415.0
9         97.5    530.0
10        99.0    718.0
11        99.5    896.0
12       100.0  27966.0

### 2.2 Reemplazar valores

In [308]:
data2 = data.copy()

In [309]:
cont = 0
for y in vars_revision_group:
    cont = cont + 1
    print("------------------------------------------------------")
    print(str(cont),". Var: ",y, sep = "")
    print(pd.concat([pd.DataFrame(base[:][y].value_counts().index, columns = ['Atributo']),
           pd.DataFrame(base[:][y].value_counts().values, columns = ['Cantidad']),
           pd.DataFrame(100*base[:][y].value_counts().values/len(base), columns = ['%Total'])], axis = 1))

------------------------------------------------------
1. Var: CODSUBSEGMENTO
  Atributo  Cantidad     %Total
0      M1N    228419  69.175325
1      X1N     89465  27.093939
2      LEN     11716   3.548120
3      P1N       603   0.182615
------------------------------------------------------
2. Var: PERFIL_TACTICO
                    Atributo  Cantidad     %Total
0              CONSUMO JOVEN     81289  24.617887
1                    CONSUMO     53402  16.172476
2     JÓVENES ALTO POTENCIAL     47843  14.488966
3                TOP CONSUMO     45086  13.654025
4   EXCLUSIVO ALTO POTENCIAL     31452   9.525050
5                  EXCLUSIVO     26676   8.078667
6                   SIN INFO     12338   3.736489
7             BAJOS INGRESOS     12010   3.637157
8                     ENALTA     10192   3.086586
9                 ESTUDIANTE      5323   1.612039
10                  JUBILADO      2553   0.773161
11              JUBILADO TOP      1624   0.491819
------------------------------------------------------
3. Var: PERFIL_DIGITAL
    Atributo  Cantidad     %Total
0    DIG MON    272711  82.588892
1  DIG NOMON     33892  10.263989
2     NO DIG     23600   7.147119
------------------------------------------------------
4. Var: FLGSEXO
  Atributo  Cantidad     %Total
0        M    208567  63.163266
1        F    121635  36.836431
------------------------------------------------------
5. Var: TIPESTCIVIL
  Atributo  Cantidad     %Total
0      SOL    224323  67.934876
1      CAS     87601  26.529438
2      SEP      8861   2.683501
3      CBS      4470   1.353713
4      CON      3754   1.136876
5      VIU      1194   0.361596
------------------------------------------------------
6. Var: TIPNIVELEDUCACIONAL
   Atributo  Cantidad     %Total
0       BAC     99242  30.054845
1       TEC     60686  18.378391
2       TIT     58006  17.566770
3       SUP     52886  16.016208
4       NDI     23099   6.995394
5       TEI     11869   3.594456
6       SEC      9531   2.886406
7       MAE      7782   2.356732
8       LIC      5549   1.680481
9       FAR       707   0.214111
10      DOC       676   0.204723
11      PRI       143   0.043307
12      ANA        27   0.008177
------------------------------------------------------
7. Var: TIPSITUACIONLABORAL
  Atributo  Cantidad     %Total
0      DEP    231233  70.027529
1      SUC     29491   8.931173
2      IND     24027   7.276433
3      NDI     21335   6.461177
4      EST     20315   6.152276
5      INF      2506   0.758927
6      JUB      1296   0.392486
------------------------------------------------------
8. Var: EDAD
    Atributo  Cantidad    %Total
0         28     17174  5.201043
1         29     16954  5.134417
2         30     16098  4.875183
3         31     14851  4.497536
4         32     14305  4.332184
5         27     14289  4.327338
6         26     13538  4.099902
7         33     13464  4.077492
8         34     13431  4.067498
9         35     12945  3.920316
10        36     12039  3.645939
11        25     11872  3.595364
12        37     11292  3.419715
13        38     10823  3.277681
14        39     10140  3.070838
15        24      9584  2.902457
16        40      9330  2.825535
17        41      8627  2.612635
18        42      7995  2.421238
19        43      7286  2.206521
20        23      6686  2.024815
21        44      6259  1.895501
22        45      5630  1.705012
23        46      5163  1.563584
24        47      4621  1.399442
25        22      4505  1.364312
26        48      4302  1.302835
27        49      3883  1.175943
28        50      3536  1.070856
29        51      3318  1.004836
..       ...       ...       ...
64        82        29  0.008782
65        84        28  0.008480
66        83        14  0.004240
67        85        14  0.004240
68        87        13  0.003937
69       117        11  0.003331
70        86        10  0.003028
71        89         7  0.002120
72        90         6  0.001817
73        91         6  0.001817
74        88         5  0.001514
75        95         3  0.000909
76         5         3  0.000909
77        13         2  0.000606
78         8         2  0.000606
79        92         2  0.000606
80       105         2  0.000606
81         3         2  0.000606
82         1         1  0.000303
83         2         1  0.000303
84         4         1  0.000303
85         7         1  0.000303
86       116         1  0.000303
87         9         1  0.000303
88        10         1  0.000303
89        11         1  0.000303
90        17         1  0.000303
91       114         1  0.000303
92       112         1  0.000303
93         0         1  0.000303

[94 rows x 3 columns]
------------------------------------------------------
9. Var: CODUBIGEO
     Atributo  Cantidad    %Total
0    150140.0     31060  9.406335
1    150122.0     15593  4.722247
2    150114.0     13592  4.116256
3    150135.0     13161  3.985730
4    150130.0     12414  3.759506
5    150132.0     12200  3.694697
6    150101.0     11296  3.420926
7    150131.0     10649  3.224986
8    150136.0      9705  2.939101
9    150117.0      9252  2.801913
10   150103.0      8892  2.692889
11    70101.0      8199  2.483018
12   150108.0      8108  2.455459
13   150110.0      7903  2.393376
14   130101.0      7554  2.287684
15   150133.0      6006  1.818881
16   150141.0      5870  1.777694
17   150121.0      5676  1.718943
18   150113.0      5341  1.617490
19   150120.0      4929  1.492718
20   150115.0      4864  1.473033
21   150142.0      4610  1.396111
22   150143.0      4582  1.387631
23   200101.0      4054  1.227730
24   140101.0      3734  1.130820
25   150116.0      3632  1.099929
26   150137.0      3513  1.063891
27   150128.0      3244  0.982426
28   150106.0      2810  0.850992
29   150105.0      2758  0.835244
..        ...       ...       ...
819   80407.0         1  0.000303
820  240202.0         1  0.000303
821  100508.0         1  0.000303
822  100507.0         1  0.000303
823  100501.0         1  0.000303
824  210105.0         1  0.000303
825   20109.0         1  0.000303
826  100317.0         1  0.000303
827   80501.0         1  0.000303
828   80505.0         1  0.000303
829   80506.0         1  0.000303
830  200606.0         1  0.000303
831  100701.0         1  0.000303
832  100803.0         1  0.000303
833  100804.0         1  0.000303
834   80305.0         1  0.000303
835   80304.0         1  0.000303
836   50404.0         1  0.000303
837   50407.0         1  0.000303
838   40127.0         1  0.000303
839   50502.0         1  0.000303
840  101104.0         1  0.000303
841   50804.0         1  0.000303
842   50910.0         1  0.000303
843   40115.0         1  0.000303
844   40114.0         1  0.000303
845   40113.0         1  0.000303
846   51005.0         1  0.000303
847   51106.0         1  0.000303
848  131007.0         1  0.000303

[849 rows x 3 columns]
------------------------------------------------------
10. Var: DEPARTAMENTO
                     Atributo  Cantidad     %Total
0   LIMA                         242974  73.583220
1   CALLAO                        16242   4.918792
2   AREQUIPA                      14700   4.451807
3   LA LIBERTAD                   12552   3.801298
4   PIURA                          7759   2.349767
5   LAMBAYEQUE                     5817   1.761644
6   ICA                            4122   1.248323
7   CUZCO                          3561   1.078428
8   ANCASH                         3508   1.062377
9   JUNIN                          3314   1.003625
10  CAJAMARCA                      2853   0.864014
11  TACNA                          1876   0.568135
12  MOQUEGUA                       1867   0.565410
13  SAN MARTIN                     1475   0.446695
14  LORETO                         1428   0.432461
15  HUANUCO                        1039   0.314655
16  UCAYALI                        1014   0.307084
17  PUNO                            985   0.298301
18  AYACUCHO                        754   0.228344
19  TUMBES                          431   0.130526
20  CERRO DE PASCO                  409   0.123863
21  AMAZONAS                        399   0.120835
22  APURIMAC                        379   0.114778
23  MADRE DE DIOS                   295   0.089339
24  HUANCAVELICA                    175   0.052998
------------------------------------------------------
11. Var: MESES_CLI
     Atributo  Cantidad    %Total
0        50.0      3131  0.948205
1        51.0      3081  0.933062
2        53.0      3042  0.921251
3        49.0      2977  0.901567
4        70.0      2977  0.901567
5        61.0      2821  0.854323
6        52.0      2779  0.841603
7        41.0      2724  0.824947
8        72.0      2722  0.824341
9        47.0      2695  0.816165
10       46.0      2627  0.795571
11       63.0      2625  0.794966
12       58.0      2619  0.793148
13       65.0      2610  0.790423
14       71.0      2582  0.781943
15       64.0      2557  0.774372
16       56.0      2515  0.761653
17       59.0      2509  0.759836
18       55.0      2502  0.757716
19       62.0      2475  0.749539
20       39.0      2440  0.738939
21       45.0      2418  0.732277
22       57.0      2395  0.725311
23       48.0      2378  0.720163
24       40.0      2366  0.716529
25       44.0      2360  0.714712
26       29.0      2351  0.711986
27       37.0      2320  0.702598
28       75.0      2260  0.684427
29       73.0      2251  0.681702
..        ...       ...       ...
436     502.0         1  0.000303
437     392.0         1  0.000303
438     426.0         1  0.000303
439     388.0         1  0.000303
440     424.0         1  0.000303
441     356.0         1  0.000303
442     348.0         1  0.000303
443     536.0         1  0.000303
444     420.0         1  0.000303
445     379.0         1  0.000303
446     540.0         1  0.000303
447     470.0         1  0.000303
448     326.0         1  0.000303
449     401.0         1  0.000303
450     544.0         1  0.000303
451     416.0         1  0.000303
452     565.0         1  0.000303
453     546.0         1  0.000303
454     452.0         1  0.000303
455     557.0         1  0.000303
456     413.0         1  0.000303
457     382.0         1  0.000303
458     429.0         1  0.000303
459     549.0         1  0.000303
460     435.0         1  0.000303
461     439.0         1  0.000303
462     572.0         1  0.000303
463     547.0         1  0.000303
464     441.0         1  0.000303
465     511.0         1  0.000303

[466 rows x 3 columns]
------------------------------------------------------
12. Var: FLG_AFLUENTE
   Atributo  Cantidad    %Total
0       0.0    207633  62.88041
1       1.0    122155  36.99391
------------------------------------------------------

13. Var: PERFIL_TACTICO_NUEVO
                    Atributo  Cantidad     %Total
0              CONSUMO JOVEN     81112  24.564283
1                    CONSUMO     52004  15.749100
2     JÓVENES ALTO POTENCIAL     47591  14.412649
3                TOP CONSUMO     44576  13.499575
4   EXCLUSIVO ALTO POTENCIAL     29144   8.826086
5                  EXCLUSIVO     26171   7.925731
6                   SIN INFO     12336   3.735884
7             BAJOS INGRESOS     11817   3.578708
8               ENALTA JOVEN      7174   2.172603
9              ENALTA ADULTO      7151   2.165638
10                ESTUDIANTE      5316   1.609919
11                  JUBILADO      2284   0.691696
12             ENALTA SENIOR      1637   0.495756
13              JUBILADO TOP      1475   0.446695
------------------------------------------------------
14. Var: FLG_PASIVO
   Atributo  Cantidad     %Total
0       1.0    329308  99.728955
1       0.0       480   0.145365
------------------------------------------------------
15. Var: FLG_ACTIVO
   Atributo  Cantidad     %Total
0       1.0    199404  60.388307
1       0.0    130384  39.486013
------------------------------------------------------
16. Var: FLG_INVERSION
   Atributo  Cantidad     %Total
0       0.0    313491  94.938871
1       1.0     16297   4.935449
------------------------------------------------------
17. Var: FLG_ACT_PAS
  Atributo  Cantidad     %Total
0      A/P    199172  60.318047
1        P    130153  39.416056
2        A       232   0.070260
3  NO PROD       231   0.069957
------------------------------------------------------
18. Var: FLG_PREST_PER
   Atributo  Cantidad     %Total
0       0.0    271837  82.324207
1       1.0     57951  17.550113
------------------------------------------------------
19. Var: FLG_TC
   Atributo  Cantidad     %Total
0       1.0    185705  56.239647
1       0.0    144083  43.634673
------------------------------------------------------
20. Var: FLG_HIP
   Atributo  Cantidad     %Total
0       0.0    315068  95.416456
1       1.0     14720   4.457864
------------------------------------------------------
21. Var: FLG_CTASUELDO
   Atributo  Cantidad     %Total
0       0.0    174621  52.882924
1       1.0    155167  46.991396
------------------------------------------------------
22. Var: FLG_CTAAHORRO
   Atributo  Cantidad    %Total
0       1.0    243846  73.84730
1       0.0     85942  26.02702
------------------------------------------------------
23. Var: FLG_FFMM
   Atributo  Cantidad     %Total
0       0.0    318536  96.466719
1       1.0     11252   3.407601
------------------------------------------------------
24. Var: CANT_FAMPROD
   Atributo  Cantidad     %Total
0       2.0    106156  32.148709
1       1.0     85079  25.765665
2       3.0     78208  23.684824
3       4.0     42653  12.917205
4       5.0     14479   4.384878
5       6.0      2568   0.777703
6       7.0       373   0.112961
7       0.0       231   0.069957
8       8.0        41   0.012417
------------------------------------------------------
25. Var: FLG_ACT_PAS_SALDO
        Atributo  Cantidad     %Total
0            A/P    158013  47.853290
1              P    139843  42.350615
2  NO PROD SALDO     20870   6.320354
3              A     11062   3.350060

In [310]:
# PERFIL_TACTICO
feature = 'PERFIL_TACTICO'
data2.loc[data2[feature] == 'CONSUMO JOVEN', feature] = 'CONS_JOV'
data2.loc[data2[feature] == 'CONSUMO', feature] = 'CONSUMO'
data2.loc[data2[feature] == 'JÓVENES ALTO POTENCIAL', feature] = 'JOV_ALTO_POT'
data2.loc[data2[feature] == 'TOP CONSUMO', feature] = 'TOP_CONS'
data2.loc[data2[feature] == 'EXCLUSIVO ALTO POTENCIAL', feature] = 'EXCLUS_ALTO_POT'
data2.loc[data2[feature] == 'EXCLUSIVO', feature] = 'EXCLUSIVO'
data2.loc[data2[feature] == 'SIN INFO', feature] = 'SIN_INFO'
data2.loc[data2[feature] == 'BAJOS INGRESOS', feature] = 'BAJOS_INGR'
data2.loc[data2[feature] == 'ENALTA', feature] = 'ENALTA'
data2.loc[(data2[feature] != 'CONS_JOV') &
          (data2[feature] != 'CONSUMO') &
          (data2[feature] != 'JOV_ALTO_POT') &
          (data2[feature] != 'TOP_CONS') &
          (data2[feature] != 'EXCLUS_ALTO_POT') &
          (data2[feature] != 'EXCLUSIVO') &
          (data2[feature] != 'SIN_INFO') &
          (data2[feature] != 'BAJOS_INGR') &
          (data2[feature] != 'ENALTA'), feature] = 'OTROS'

In [311]:
# TIPESTCIVIL
feature = 'TIPESTCIVIL'
data2.loc[(data2[feature] != 'SOL') &
          (data2[feature] != 'CAS'), feature] = 'OTROS'

In [312]:
# TIPSITUACIONLABORAL
feature = 'TIPSITUACIONLABORAL'
data2.loc[(data2[feature] != 'DEP') &
          (data2[feature] != 'SUC') &
          (data2[feature] != 'IND') &
          (data2[feature] != 'NDI') &
          (data2[feature] != 'NDI') &
          (data2[feature] != 'NDI') &
          (data2[feature] != 'EST'), feature] = 'OTROS'

In [313]:
# TIPNIVELEDUCACIONAL
feature = 'TIPNIVELEDUCACIONAL'
data2.loc[(data2[feature] != 'BAC') &
          (data2[feature] != 'TEC') &
          (data2[feature] != 'TIT') &
          (data2[feature] != 'SUP') &
          (data2[feature] != 'NDI') &
          (data2[feature] != 'TEI') &
          (data2[feature] != 'MAE'), feature] = 'OTROS'

In [314]:
# EDAD
feature = 'EDAD'
data2.loc[data2[feature] <= 21, feature] = 21
data2.loc[data2[feature] >= 62, feature] = 62

In [315]:
# CODUBIGEO
feature = 'CODUBIGEO'
data2.loc[(data2[feature] != 150140) &
          (data2[feature] != 150122) &
          (data2[feature] != 150114) &
          (data2[feature] != 150135) &
          (data2[feature] != 150130) &
          (data2[feature] != 150132) &
          (data2[feature] != 150101) &
          (data2[feature] != 150131) &
          (data2[feature] != 150136) &
          (data2[feature] != 150117) &
          (data2[feature] != 150103) &
          (data2[feature] != 70101) &
          (data2[feature] != 150108) &
          (data2[feature] != 150110) &
          (data2[feature] != 130101) &
          (data2[feature] != 150133) &
          (data2[feature] != 150141) &
          (data2[feature] != 150121) &
          (data2[feature] != 200101), feature] = 999999

In [312]:
# DEPARTAMENTO
feature = 'DEPARTAMENTO'
data2[feature] = data2[feature].map(lambda x: x.replace(' ', ''))
data2.loc[data2[feature] == 'LA LIBERTAD', feature] = 'LA_LIBERTAD'
data2.loc[(data2[feature] != 'DEP') &
          (data2[feature] != 'SUC') &
          (data2[feature] != 'IND') &
          (data2[feature] != 'NDI') &
          (data2[feature] != 'NDI') &
          (data2[feature] != 'NDI') &
          (data2[feature] != 'EST'), feature] = 'OTROS'

In [318]:
# FLG_ACT_PAS
feature = 'FLG_ACT_PAS'
data2.loc[data2[feature] == 'A/P', feature] = 'AP'
data2.loc[data2[feature] == 'P', feature] = 'P'
data2.loc[(data2[feature] != 'AP') &
          (data2[feature] != 'P'), feature] = 'OTROS'

In [316]:
# FLG_ACT_PAS_SALDO
feature = 'FLG_ACT_PAS_SALDO'
data2.loc[data2[feature] == 'A/P', feature] = 'AP'
data2.loc[data2[feature] == 'P', feature] = 'P'
data2.loc[(data2[feature] != 'AP') &
          (data2[feature] != 'P'), feature] = 'OTROS'

In [319]:
cont = 0
for y in vars_revision_group:
    cont = cont + 1
    print("------------------------------------------------------")
    print(str(cont),". Var: ",y, sep = "")
    print(pd.concat([pd.DataFrame(data2[:][y].value_counts().index, columns = ['Atributo']),
           pd.DataFrame(data2[:][y].value_counts().values, columns = ['Cantidad']),
           pd.DataFrame(100*data2[:][y].value_counts().values/len(data2), columns = ['%Total'])], axis = 1))

------------------------------------------------------
1. Var: CODSUBSEGMENTO
  Atributo  Cantidad     %Total
0      M1N    228419  69.175325
1      X1N     89465  27.093939
2      LEN     11716   3.548120
3      P1N       603   0.182615
------------------------------------------------------
2. Var: PERFIL_TACTICO
          Atributo  Cantidad     %Total
0         CONS_JOV     81289  24.617887
1          CONSUMO     53402  16.172476
2     JOV_ALTO_POT     47843  14.488966
3         TOP_CONS     45086  13.654025
4  EXCLUS_ALTO_POT     31452   9.525050
5        EXCLUSIVO     26676   8.078667
6         SIN_INFO     12753   3.862170
7       BAJOS_INGR     12010   3.637157
8           ENALTA     10192   3.086586
9            OTROS      9500   2.877018
------------------------------------------------------
3. Var: PERFIL_DIGITAL
    Atributo  Cantidad     %Total
0    DIG MON    272711  82.588892
1  DIG NOMON     33892  10.263989
2     NO DIG     23600   7.147119
------------------------------------------------------
4. Var: FLGSEXO
  Atributo  Cantidad     %Total
0        M    208568  63.163569
1        F    121635  36.836431
------------------------------------------------------
5. Var: TIPESTCIVIL
  Atributo  Cantidad     %Total
0      SOL    224323  67.934876
1      CAS     87601  26.529438
2    OTROS     18279   5.535686
------------------------------------------------------
6. Var: TIPNIVELEDUCACIONAL
  Atributo  Cantidad     %Total
0      BAC     99242  30.054845
1      TEC     60686  18.378391
2      TIT     58006  17.566770
3      SUP     52886  16.016208
4      NDI     23099   6.995394
5    OTROS     16633   5.037204
6      TEI     11869   3.594456
7      MAE      7782   2.356732
------------------------------------------------------
7. Var: TIPSITUACIONLABORAL
  Atributo  Cantidad     %Total
0      DEP    231233  70.027529
1      SUC     29491   8.931173
2      IND     24027   7.276433
3      NDI     21335   6.461177
4      EST     20315   6.152276
5    OTROS      3802   1.151413
------------------------------------------------------
8. Var: EDAD
    Atributo  Cantidad    %Total
0         28     17174  5.201043
1         29     16954  5.134417
2         30     16098  4.875183
3         31     14851  4.497536
4         32     14305  4.332184
5         27     14289  4.327338
6         26     13538  4.099902
7         33     13464  4.077492
8         34     13431  4.067498
9         35     12945  3.920316
10        36     12039  3.645939
11        25     11872  3.595364
12        37     11292  3.419715
13        38     10823  3.277681
14        39     10140  3.070838
15        24      9584  2.902457
16        40      9330  2.825535
17        41      8627  2.612635
18        62      8347  2.527839
19        42      7995  2.421238
20        43      7286  2.206521
21        23      6686  2.024815
22        44      6259  1.895501
23        45      5630  1.705012
24        21      5493  1.663522
25        46      5163  1.563584
26        47      4621  1.399442
27        22      4505  1.364312
28        48      4302  1.302835
29        49      3883  1.175943
30        50      3536  1.070856
31        51      3318  1.004836
32        52      3082  0.933365
33        53      2913  0.882185
34        54      2762  0.836455
35        55      2399  0.726523
36        56      2343  0.709564
37        57      2199  0.665954
38        58      1952  0.591152
39        59      1704  0.516046
40        60      1579  0.478191
41        61      1490  0.451238
------------------------------------------------------
9. Var: CODUBIGEO
    Atributo  Cantidad     %Total
0   999999.0    128744  38.989349
1   150140.0     31335   9.489617
2   150122.0     15593   4.722247
3   150114.0     13592   4.116256
4   150135.0     13161   3.985730
5   150130.0     12414   3.759506
6   150132.0     12200   3.694697
7   150101.0     11296   3.420926
8   150131.0     10649   3.224986
9   150136.0      9705   2.939101
10  150117.0      9252   2.801913
11  150103.0      8892   2.692889
12   70101.0      8199   2.483018
13  150108.0      8108   2.455459
14  150110.0      7903   2.393376
15  130101.0      7554   2.287684
16  150133.0      6006   1.818881
17  150141.0      5870   1.777694
18  150121.0      5676   1.718943
19  200101.0      4054   1.227730
------------------------------------------------------
10. Var: DEPARTAMENTO
                     Atributo  Cantidad     %Total
0   LIMA                         242974  73.583220
1   CALLAO                        16242   4.918792
2   AREQUIPA                      14700   4.451807
3   LA LIBERTAD                   12552   3.801298
4   PIURA                          7759   2.349767
5   LAMBAYEQUE                     5817   1.761644
6   ICA                            4122   1.248323
7   CUZCO                          3561   1.078428
8   ANCASH                         3508   1.062377
9   JUNIN                          3314   1.003625
10  CAJAMARCA                      2853   0.864014
11  TACNA                          1876   0.568135
12  MOQUEGUA                       1867   0.565410
13  SAN MARTIN                     1475   0.446695
14  LORETO                         1428   0.432461
15  HUANUCO                        1039   0.314655
16  UCAYALI                        1014   0.307084
17  PUNO                            985   0.298301
18  AYACUCHO                        754   0.228344
19  TUMBES                          431   0.130526
20  CERRO DE PASCO                  409   0.123863
21  AMAZONAS                        399   0.120835
22  APURIMAC                        379   0.114778
23  MADRE DE DIOS                   295   0.089339
24                       LIMA       275   0.083282
25  HUANCAVELICA                    175   0.052998
------------------------------------------------------
11. Var: MESES_CLI
     Atributo  Cantidad    %Total
0        50.0      3131  0.948205
1        51.0      3081  0.933062
2        53.0      3042  0.921251
3        49.0      2977  0.901567
4        70.0      2977  0.901567
5        61.0      2821  0.854323
6        52.0      2779  0.841603
7        41.0      2724  0.824947
8        72.0      2722  0.824341
9        47.0      2695  0.816165
10       46.0      2627  0.795571
11       63.0      2625  0.794966
12       58.0      2619  0.793148
13       65.0      2610  0.790423
14       71.0      2582  0.781943
15       64.0      2557  0.774372
16       56.0      2515  0.761653
17       59.0      2509  0.759836
18       55.0      2502  0.757716
19       62.0      2475  0.749539
20       39.0      2440  0.738939
21       45.0      2418  0.732277
22       57.0      2395  0.725311
23       48.0      2378  0.720163
24       40.0      2366  0.716529
25       44.0      2360  0.714712
26       29.0      2351  0.711986
27       37.0      2320  0.702598
28       75.0      2260  0.684427
29       73.0      2251  0.681702
..        ...       ...       ...
436     502.0         1  0.000303
437     392.0         1  0.000303
438     426.0         1  0.000303
439     388.0         1  0.000303
440     424.0         1  0.000303
441     356.0         1  0.000303
442     348.0         1  0.000303
443     536.0         1  0.000303
444     420.0         1  0.000303
445     379.0         1  0.000303
446     540.0         1  0.000303
447     470.0         1  0.000303
448     326.0         1  0.000303
449     401.0         1  0.000303
450     544.0         1  0.000303
451     416.0         1  0.000303
452     565.0         1  0.000303
453     546.0         1  0.000303
454     452.0         1  0.000303
455     557.0         1  0.000303
456     413.0         1  0.000303
457     382.0         1  0.000303
458     429.0         1  0.000303
459     549.0         1  0.000303
460     435.0         1  0.000303
461     439.0         1  0.000303
462     572.0         1  0.000303
463     547.0         1  0.000303
464     441.0         1  0.000303
465     511.0         1  0.000303

[466 rows x 3 columns]
------------------------------------------------------
12. Var: FLG_AFLUENTE
   Atributo  Cantidad    %Total
0       0.0    208048  63.00609
1       1.0    122155  36.99391
------------------------------------------------------
13. Var: PERFIL_TACTICO_NUEVO
                    Atributo  Cantidad     %Total
0              CONSUMO JOVEN     81527  24.689963
1                    CONSUMO     52004  15.749100
2     JÓVENES ALTO POTENCIAL     47591  14.412649
3                TOP CONSUMO     44576  13.499575
4   EXCLUSIVO ALTO POTENCIAL     29144   8.826086
5                  EXCLUSIVO     26171   7.925731
6                   SIN INFO     12336   3.735884
7             BAJOS INGRESOS     11817   3.578708
8               ENALTA JOVEN      7174   2.172603
9              ENALTA ADULTO      7151   2.165638
10                ESTUDIANTE      5316   1.609919
11                  JUBILADO      2284   0.691696
12             ENALTA SENIOR      1637   0.495756
13              JUBILADO TOP      1475   0.446695
------------------------------------------------------
14. Var: FLG_PASIVO
   Atributo  Cantidad     %Total
0       1.0    329308  99.728955
1       0.0       895   0.271045
------------------------------------------------------
15. Var: FLG_ACTIVO
   Atributo  Cantidad     %Total
0       1.0    199404  60.388307
1       0.0    130799  39.611693
------------------------------------------------------
16. Var: FLG_INVERSION
   Atributo  Cantidad     %Total
0       0.0    313906  95.064551
1       1.0     16297   4.935449
------------------------------------------------------

17. Var: FLG_ACT_PAS
  Atributo  Cantidad     %Total
0       AP    199172  60.318047
1        P    130153  39.416056
2    OTROS       878   0.265897
------------------------------------------------------
18. Var: FLG_PREST_PER
   Atributo  Cantidad     %Total
0       0.0    272252  82.449887
1       1.0     57951  17.550113
------------------------------------------------------
19. Var: FLG_TC
   Atributo  Cantidad     %Total
0       1.0    185705  56.239647
1       0.0    144498  43.760353
------------------------------------------------------
20. Var: FLG_HIP
   Atributo  Cantidad     %Total
0       0.0    315483  95.542136
1       1.0     14720   4.457864
------------------------------------------------------
21. Var: FLG_CTASUELDO
   Atributo  Cantidad     %Total
0       0.0    175036  53.008604
1       1.0    155167  46.991396
------------------------------------------------------
22. Var: FLG_CTAAHORRO
   Atributo  Cantidad   %Total
0       1.0    243846  73.8473
1       0.0     86357  26.1527
------------------------------------------------------
23. Var: FLG_FFMM
   Atributo  Cantidad     %Total
0       0.0    318951  96.592399
1       1.0     11252   3.407601
------------------------------------------------------
24. Var: CANT_FAMPROD
   Atributo  Cantidad     %Total
0       2.0    106156  32.148709
1       1.0     85079  25.765665
2       3.0     78208  23.684824
3       4.0     42653  12.917205
4       5.0     14479   4.384878
5       6.0      2568   0.777703
6       0.0       646   0.195637
7       7.0       373   0.112961
8       8.0        41   0.012417
------------------------------------------------------
25. Var: FLG_ACT_PAS_SALDO
  Atributo  Cantidad     %Total
0       AP    158013  47.853290
1        P    139843  42.350615
2    OTROS     32347   9.796095